### ISSUE TITLE
Security issues

### ISSUE THREAD

**Issue by gwolfer** [mouse-reeve/infinite_gnossienne#6]
When running on Chrome Version 69.0.3497.100 (Official Build) (64-bit)
______________________
The Web Audio autoplay policy will be re-enabled in Chrome 70 (October 2018). Please check that your website is compatible with it. https://goo.gl/7K7WLu
createPiano @ gnossiennes.min.js:26
gleitz.github.io/midi-js-soundfonts/MusyngKite/acoustic_grand_piano-mp3.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
soundfont-player.min.js:1 Uncaught (in promise) Error: Network Error
    at XMLHttpRequest.req.onerror (soundfont-player.min.js:1)

**Comment by gwolfer** [comment]
And here is a capture:

![capture](https://user-images.githubusercontent.com/3954855/47949038-c58e2f00-df44-11e8-951d-5ea42b30ebec.png)

**Comment by mouse-reeve** [comment]
Huh, I've tried it on version 68.something and just now on version 70.0.3538.77 and I've never had a problem loading the soundfont. Do you have any browser extensions that impact external requests, like privacy badger or an ad blocker? I get the same behavior if I block `gleitz.github.io` in privacy badger.

**Comment by gwolfer** [comment]
Yes you are right, it came from an ad-blocker
