### ISSUE TITLE
how to run it

### ISSUE THREAD

**Issue by DaveGeneral** [mouse-reeve/infinite_gnossienne#7]
hey, mouse, love your work, can you give me some instructions to deploy and run it? I pip install the requirements and type python app.py but it doesn't goes on the right way..

**Comment by mouse-reeve** [comment]
That's my bad, I didn't include how to install the external javascript dependencies. As a quick fix, I've just added them to the git repo. If you do a git pull, you should have the right dependencies and be able to run the code

**Comment by mouse-reeve** [comment]
let me know if this gets it working for you!
